import React from 'react';
import { AlertCircle, CheckCircle2, Clock3, ShieldAlert, ShieldCheck, TriangleAlert } from 'lucide-react';
export function Card({ children, className = '' }) { return <section className={`rounded-xl border border-slate-700 bg-surface shadow-panel ${className}`}>{children}</section>; }
export function Button({ children, variant = 'primary', className = '', ...props }) { const styles = { primary: 'bg-primary hover:bg-blue-500 text-white', secondary: 'bg-slate-700 hover:bg-slate-600 text-white', danger: 'bg-danger hover:bg-red-500 text-white' }; return <button className={`inline-flex min-h-11 items-center justify-center gap-2 rounded-lg px-4 font-medium transition focus:outline-none focus:ring-2 focus:ring-primary focus:ring-offset-2 focus:ring-offset-ink disabled:cursor-not-allowed disabled:opacity-60 ${styles[variant]} ${className}`} {...props}>{children}</button>; }
const statusConfig = { safe: [ShieldCheck, 'Safe', 'bg-safe/15 text-green-300 ring-green-500/30'], suspicious: [TriangleAlert, 'Suspicious', 'bg-warning/15 text-amber-300 ring-amber-500/30'], malicious: [ShieldAlert, 'Malicious', 'bg-danger/15 text-red-300 ring-red-500/30'], unknown: [Clock3, 'Unknown', 'bg-slate-500/20 text-slate-300 ring-slate-500/30'] };
export function VerdictBadge({ verdict }) { const [Icon, label, style] = statusConfig[verdict] || statusConfig.unknown; return <span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1 text-sm font-semibold ring-1 ${style}`}><Icon size={16} aria-hidden="true" />{label}</span>; }
export function ErrorMessage({ children }) { return <p role="alert" className="mt-3 flex items-start gap-2 text-sm text-red-300"><AlertCircle size={17} className="mt-0.5 shrink-0" />{children}</p>; }
export function EmptyState({ title, description, action }) { return <Card className="p-8 text-center"><CheckCircle2 className="mx-auto mb-3 text-slate-500" size={34} /><h2 className="font-heading text-xl font-semibold">{title}</h2><p className="mx-auto mt-2 max-w-md text-slate-400">{description}</p>{action && <div className="mt-5">{action}</div>}</Card>; }
export function Spinner({ label = 'Loading' }) { return <div className="flex items-center gap-3 text-slate-300" role="status"><span className="h-5 w-5 animate-spin rounded-full border-2 border-slate-500 border-t-primary" /><span>{label}</span></div>; }
